export enum userList {
    FETCH = 'USER_LIST::FETCH',
    FETCH_SUCCESS = 'USER_LIST::FETCH_SUCCESS',
    FETCH_FAILURE = 'USER_LIST::FETCH_FAILURE',
    SET_PAGE = 'USER_LIST::SET_PAGE',
    SET_PER_PAGE = 'USER_LIST::SET_PER_PAGE',
}